#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# If you want to allow non-ASCII filenames set this variable to true.
project_root=$(git rev-parse --show-toplevel)
model_path="${project_root}/model"

git diff --cached --name-only | grep xcos | while read -r model ; do
    echo "Indenting model at: $project_root/$model"
    $project_root/scripts/indent_model.sh "$project_root/$model"
    git add "$project_root/$model"
done

# Redirect output to stderr.
exec 1>&2
